#!/usr/bin/env python3
"""Compare the app's name day list with the one fetched from Wikipedia.

Usage:
    python3 scripts/compare_namedays.py

Reads app/src/main/assets/namedays.json and scripts/namedays_wikipedia.json
and writes a Markdown report to scripts/namedays_comparison.md.
"""

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
APP_FILE = ROOT / "app/src/main/assets/namedays.json"
WIKI_FILE = ROOT / "scripts/namedays_wikipedia.json"
REPORT_FILE = ROOT / "scripts/namedays_comparison.md"

LANGS = {"fi": "Finnish", "sv": "Swedish"}


def fmt(names):
    return ", ".join(names) if names else "—"


def main():
    app = json.loads(APP_FILE.read_text(encoding="utf-8"))
    wiki = json.loads(WIKI_FILE.read_text(encoding="utf-8"))
    links = dict(
        line.split("\t")
        for line in (ROOT / "scripts/wikipedia_links.txt").read_text(encoding="utf-8").split("\n")
        if line
    )

    rows = {lang: [] for lang in LANGS}
    stats = {lang: {"days": 0, "exact": 0, "order": 0, "diff": 0,
                    "missing": 0, "extra": 0} for lang in LANGS}

    for key in sorted(set(app) | set(wiki)):
        for lang in LANGS:
            ours = app.get(key, {}).get(lang, [])
            theirs = wiki.get(key, {}).get(lang, [])
            s = stats[lang]
            s["days"] += 1
            if ours == theirs:
                s["exact"] += 1
                continue
            if sorted(ours) == sorted(theirs):
                s["order"] += 1
                continue
            missing = [n for n in theirs if n not in ours]
            extra = [n for n in ours if n not in theirs]
            s["diff"] += 1
            s["missing"] += len(missing)
            s["extra"] += len(extra)
            rows[lang].append((key, ours, theirs, missing, extra))

    out = ["# Name day comparison: app vs. Finnish Wikipedia", ""]
    out.append(f"App data: `{APP_FILE.relative_to(ROOT)}`  ")
    out.append(f"Wikipedia data: `{WIKI_FILE.relative_to(ROOT)}` "
               "(generated by `scripts/fetch_namedays.py`)")
    out.append("")
    out.append("## Summary")
    out.append("")
    out.append("| Calendar | Days | Identical | Same names, different order "
               "| Different | Names missing from app | Extra names in app |")
    out.append("|---|---|---|---|---|---|---|")
    for lang, label in LANGS.items():
        s = stats[lang]
        out.append(f"| {label} | {s['days']} | {s['exact']} | {s['order']} "
                   f"| {s['diff']} | {s['missing']} | {s['extra']} |")
    out.append("")

    for lang, label in LANGS.items():
        out.append(f"## {label} calendar — {len(rows[lang])} differing days")
        out.append("")
        out.append("| Date | App | Wikipedia | Missing from app | Extra in app |")
        out.append("|---|---|---|---|---|")
        for key, ours, theirs, missing, extra in rows[lang]:
            date = f"[{key}]({links[key]})" if key in links else key
            out.append(f"| {date} | {fmt(ours)} | {fmt(theirs)} "
                       f"| {fmt(missing)} | {fmt(extra)} |")
        out.append("")

    REPORT_FILE.write_text("\n".join(out), encoding="utf-8")
    for lang, label in LANGS.items():
        s = stats[lang]
        print(f"{label}: {s['exact']} identical, {s['order']} reordered, "
              f"{s['diff']} different ({s['missing']} missing, {s['extra']} extra names)")
    print(f"Report written to {REPORT_FILE.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
